<link href="<?php echo $site_url; ?>/css/jquery-ui.css" rel="stylesheet">
<link href="<?php echo $site_url; ?>/css/bootstrap.css" rel="stylesheet">
<link href="<?php echo $site_url; ?>/css/bootstrap-theme.css" rel="stylesheet">
<link href="<?php echo $site_url; ?>/css/jquery.datetimepicker.css" rel="stylesheet">
<link href="<?php echo $site_url; ?>/css/font-awesome.css" rel="stylesheet">
<link href="<?php echo $site_url; ?>/css/fonts.css" rel="stylesheet">
<link href="<?php echo $site_url; ?>/css/presets.css?v=0.5.4" rel="stylesheet">
<link href="<?php echo $site_url; ?>/css/style.css?v=0.5.4" rel="stylesheet">
<link href="<?php echo $site_url; ?>/css/media.css?v=0.5.4" rel="stylesheet">
<link href="<?php echo $site_url; ?>/css/print.css?v=0.5.4" rel="stylesheet">